name: Testing workflows for colcon-bundle
on:
  pull_request:
  push:
    branches:
      - master
      - dev
  schedule:
    - cron: '0 * * * *'
jobs:
  test:
    env:
      GO111MODULE: on
    strategy:
      matrix:
        go-version: [ 1.15.x, 1.16.x ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Golang
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Dependencies
        run: |
          go get github.com/mitchellh/gox
          go get github.com/golang/mock/gomock
          go install github.com/golang/mock/mockgen
      - name: Check Format
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
        if: matrix.os == 'ubuntu-latest'
      - name: Build
        run: |
          go build ./...
      - name: Generate
        run: go generate ./...
      - name: Test
        run: go test -v -race ./...
      - name: Build Binaries
        run: gox -osarch="darwin/amd64 windows/amd64 linux/amd64 linux/arm" -output="bundle-helper.{{.OS}}.{{.Arch}}" -verbose ./cmd/cli; fi
        if: ${{ matrix.go-version == '1.16.x' && matrix.os == 'ubuntu-latest' }}